services:
  - type: web
    name: locker-padel-admin
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ''
    startCommand: ''
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: # Add your app key or generate one via php artisan key:generate
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d143u4mmcj7s738l1iug-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: lockerpadel
      - key: DB_USERNAME
        value: lockerpadel_user
      - key: DB_PASSWORD
        value: Db7lLSM6PNEcPlPWKP7lQEVkQKMVi1T6
      - key: VITE_APP_NAME
        value: LockerPadel
      - key: ASSET_URL
        value: https://locker-padel-admin.onrender.com
  - type: postgres
    name: locker-padel-db
    plan: free
    region: oregon
    username: render_user
    password: render_password
    databaseName: locker_padel
