services:
  - type: web
    name: locker-padel-admin
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ''
    startCommand: ''
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: # Add your app key or generate one via php artisan key:generate
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: locker-padel-db.internal
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: locker_padel
      - key: DB_USERNAME
        value: render_user
      - key: DB_PASSWORD
        value: render_password
  - type: postgres
    name: locker-padel-db
    plan: free
    region: oregon
    username: render_user
    password: render_password
    databaseName: locker_padel
